function Hd = p_02_IIR
%P_02_IIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.10 and DSP System Toolbox 9.12.
% Generated on: 01-Jun-2023 22:00:40

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

Fpass = 0.0625;      % Passband Frequency
Fstop = 0.2041;      % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 20;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
