clear all; close all; clc;
load('G_data.mat');
load('filter4_FIR.mat');
load('filter4_IIR.mat');
P_x4 = mean(abs(x4).^2);
SNR = 10;
P_n = P_x4 * 10^(-SNR/10);
v = sqrt(P_n)*randn(1,length(x4));
x4_f = fft(x4);
x4_r = x4+v;
x4_r_f = fft(x4_r);
x_filt_FIR = filter(Hd,x4);
x_filt_IIR = filter(Hd_IIR,x4);
y_FIR = filter(Hd,x4_r);
y_IIR = filter(Hd_IIR,x4_r);
scal = max(x4)/max(y_FIR);
scal2 = max(x4)/max(y_IIR);
norm_y_FIR = y_FIR*scal;
norm_y_IIR = y_IIR*scal2;
delay = 11;
delay2 = 29;
noise = mean(abs(y_FIR(delay:end)-x4(1:end-delay+1)).^2);
noise2 = mean(abs(y_IIR(delay2:end)-x4(1:end-delay2+1)).^2);
SNRo_FIR = 10*log10(mean(abs(x_filt_FIR).^2)/noise);
SNRo_IIR = 10*log10(mean(abs(x_filt_IIR).^2)/noise2);

figure();plot(x4_r);
f = linspace(-1/2,1/2,length(x4_r_f));
figure();plot(f,abs(fftshift(x4_f)));hold on;plot(f,abs(fftshift(x4_r_f)));
figure();plot(x4);hold on;plot(abs(norm_y_FIR(delay:end)));
figure();plot(x4);hold on;plot(abs(norm_y_IIR(delay2:end)));